Model Folder Contents
UCLH-Foundry/Model-Seedling pull request #1
Opened 2023-03-28 23:09 UTC by martinpeck

2023-04-03 15:49 UTC, martinpeck commented
@tdgfrost can you move this from Draft to Published if you're ready for review?

I've pushed the initial folder structure to `main` so can can you also rebased on `main` please?

2023-04-04 12:53 UTC, ahmed-alhindawi commented on model/conda.yml
> +  - pip:
Could please remove the `polars` (the template doesn't require `polars`) and the duplicate `mlflow` requirements here

2023-04-04 12:54 UTC, ahmed-alhindawi requested changes
If we can clean up the `pip` requirements, then personally I think the pull request is in good shape

2023-04-04 13:02 UTC, ahmed-alhindawi approved these changes

2023-04-04 13:17 UTC, merged